add file extension for MinIO
TaleLin/lin-cms-spring-boot pull request #139
Opened 2020-11-22 04:54 UTC by lhsheild

## 添加
增加一个MinIO的文件上传扩展

2020-11-24 10:46 UTC, juzi214032 commented
是这个 minio 吗
https://github.com/minio/minio

2020-11-24 11:53 UTC, lhsheild commented
> 是这个 minio 吗
> https://github.com/minio/minio

对

2020-12-07 14:58 UTC, juzi214032 commented
请将您的代码基于 develop 分支 checkout 再提交 pr，不要基于master 分支 checkout

2020-12-07 14:58 UTC, juzi214032 requested changes
修改分支 base

2020-12-09 13:31 UTC, closed without merging